#!/bin/bash

# check if is root
function isRoot () {
    if [ `id -u` != "0" ]; then
        echo Command must be ran by root!
        exit 1
    fi
}

# installation
function installation () {
    install -m 400 lib/systemd/system/ipUpdaterd.service /etc/systemd/system/ipUpdaterd.service
    install -m 600 usr/local/etc/ipUpdaterd.conf /usr/local/etc/ipUpdaterd.conf
    install -m 700 usr/local/sbin/ipUpdaterd /usr/local/sbin/ipUpdaterd
    
    # restore SELinux stuff
    restorecon /etc/systemd/system/ipUpdaterd.service &> /dev/null
}

# configure
function configure () {
    echo -n "What's your login? "
    read 'login'

    echo -n "What's your password? "
    read -s 'password'
    password=$(echo -n $password | base64)

    echo -ne "\nWhat hostname to use? (example: myhost.mydomain.com) "
    read 'host'

    echo -n "Do you want me to get your IP from an interface? (example: no | eth0, wlan0, ppp0, etc) "
    read 'interface'

    case $interface in
        n|no|nO|N|NO|No|null)
            ip=
            ;;
        *)
            ip=$(ip -4 address show ${interface} |/bin/awk -F'[/ ]' '/inet/{print$6}')
            ;;
    esac
}

function confirm () {
    echo -n " \

Is this correct?

    Login:      ${login}
    Password:   <hidden>
    Host:       ${host}
    interface:  ${interface}

    answer (yes|no) "
    read 'confirmation'
}

function commit () {
    sed -ri "s@login='<some user>'@login=${login}@g" /usr/local/etc/ipUpdaterd.conf
    sed -ri "s@password='<some cool password base64 encoded>'@password='${password}'@g" /usr/local/etc/ipUpdaterd.conf
    sed -ri "s@host='<some, already registered, host>'@host='${host}'@g" /usr/local/etc/ipUpdaterd.conf
    sed -ri "s@myip=''@myip='${ip}'@g" /usr/local/etc/ipUpdaterd.conf
}

function message ()
{
    cat <<EOF

Once you edit /usr/local/etc/ipUpdard.conf, Your configuration is done. 
Feel free to start the service by typing:
    su -c 'systemctl start ipUpdaterd.service'

And, if you want this service to start at boot, activate it:
    su -c 'systemctl enable ipUpdaterd.service'

Thank you for using it!

EOF

}

# check if it's user has root priviledges
isRoot

# obtain info
#until [[ $confirmation == 'yes' ]]; do
#    configure
#    confirm
#done

# install files
installation

# write changes
commit

# finalization message
message

exit 0
