#!/bin/bash
# Last Update: Mon 20 Dec 2010 11:24:26 AM CST 
#
# Renich Bon Ciric <renich@intranetgb.com>
# GPLv3
#
# Simple IP updater for DNSExit: http://dnsexit.com/

# get configuration file
conf=/usr/local/etc/ipUpdaterd.conf
source $conf

# do
(while :; do
    # DNSExit
    /usr/bin/curl -s -G -d "login=${DNSExit['login']}" -d "password=${DNSExit['password']}" -d "host=${DNSExit['host']}" -d "myip=${Global['myIP']}" ${DNSExit['service']} &> ${DNSExit['log']}
    
    if [ $? == 0 ];then
        logger -p daemon.info "DNSEXIT: this IP has been updated successfully."
    else
        logger -p daemon.info "IP update error. Check configuration, network or... something..."
    fi

    # OpenDNS
    /usr/bin/curl -k -s -G -m 60 -u ${OpenDNS['login']}:${OpenDNS['password']} -d "host=${OpenDNS['host']}" -d "ip=${Global['myIP']}" ${OpenDNS['service']} &> ${OpenDNS['log']}

    sleep 10m
done) & disown -h -ar $!
